# mysite_uwsgi.ini file
[uwsgi]

# Django-related settings
# the base directory (full path)
chdir           = /opt/myenv/wasaboo
# Django's wsgi file
module          = wasaboo.wsgi.application
# the virtualenv (full path)
home            = /opt/myenv/wasaboo

plugins = python
virtualenv = /opt/myenv

# process-related settings
# master
master          = true
# maximum number of worker processes
processes       = 10
# the socket (use the full path to be safe
#socket          = /opt/myenv/sispat/sispat.sock
# ... with appropriate permissions - may be needed
#chmod-socket    = 664
# clear environment on exit
vacuum          = true


